GRANT SELECT ON L13692334.L06_ATLETA TO Teste19 WITH GRANT OPTION;
GRANT SELECT ON L13692334.L03_MODALIDADE TO Teste19 WITH GRANT OPTION;

--b)
CREATE TABLE L12_MAT_ESPORTIVO (
    ID NUMBER PRIMARY KEY,
    Descricao VARCHAR2(255),
    Preco NUMBER,
    Atleta VARCHAR2(10),
    FOREIGN KEY (Atleta) REFERENCES L06_ATLETA(Passaporte)
);
GRANT REFERENCES ON L13692334.L12_MAT_ESPORTIVO TO Teste19; --precisa ser feito antes da criação da tabela estoque na conexão teste19
INSERT INTO L12_MAT_ESPORTIVO (ID, Descricao, Preco, Atleta)
VALUES (1, 'Bola de Futebol', 100.00, 'A001'); 

INSERT INTO L12_MAT_ESPORTIVO (ID, Descricao, Preco, Atleta)
VALUES (2, 'Raquete de Tênis', 250.00, 'A002'); 
--c)
CREATE TABLE L14_VENDAS (
    ID NUMBER PRIMARY KEY,
    ITEM NUMBER,  
    QTD NUMBER,  
    VALOR_TOTAL NUMBER  
);
--trigger
CREATE OR REPLACE TRIGGER atualizar_estoque_venda
AFTER INSERT ON L14_VENDAS FOR EACH ROW
BEGIN
    UPDATE Teste19.L13_ESTOQUE
    SET QTD_ESTOQUE = QTD_ESTOQUE - :NEW.QTD
    WHERE Mat_Esportivo_ID = :NEW.ITEM;
END;
/
--inserindo dados pra testar o trigger
INSERT INTO L14_VENDAS (ID, ITEM, QTD, VALOR_TOTAL)
VALUES (1, 1, 5, 500.00); 

INSERT INTO L14_VENDAS (ID, ITEM, QTD, VALOR_TOTAL)
VALUES (2, 2, 3, 750.00); 