--ii)
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
    NAME 'AtualizaVencedorDisputa';

UPDATE L05_DISPUTA
SET VENCEDOR = 'Brasil'
WHERE ID = 32;

-- b) SERIALIZABLE:
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
    NAME 'Atualiza_Vencedor_Disputa';

UPDATE L05_DISPUTA
SET VENCEDOR = 'Brasil'
WHERE ID = 32;    

COMMIT;
ROLLBACK;
