DROP TABLE L11_TRANSMITE;
DROP TABLE L10_MIDIA;
DROP TABLE L09_PATROCINA;
DROP TABLE L08_PATROCINADOR;
DROP TABLE L07_JOGA;
DROP TABLE L06_ATLETA;
DROP TABLE L05_DISPUTA;
DROP TABLE L04_LOCAL;
DROP TABLE L03_MODALIDADE;
DROP TABLE L02_OLIMPIADA;
DROP TABLE L01_PAIS;

--drop de sinonimos para recriacao em seguida
BEGIN
   FOR rec IN (SELECT synonym_name FROM user_synonyms) LOOP
      EXECUTE IMMEDIATE 'DROP SYNONYM ' || rec.synonym_name;
   END LOOP;
END;